In [2]:
#import math
import numpy as np
import random
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from nltk import pos_tag

np.set_printoptions(linewidth=400)   # optional: widens column of numpy array display

In [3]:
# HOW-TO only: uses numbers (i.e. feature values), to demonstrate a way (not the only way) to load X, y, Xtest, and ytest
# You will not do this (load number from a file).  You'll get your X, y, Xtest, and ytest values by extracting features from the review
X = []
y = []
with open("demo-train.txt", 'r', encoding='utf8') as f:
    for line in f:
        if line != "":
            vals = line.split()
            X.append([float(val) for val in vals[:-1]])
            y.append(int(vals[-1]))
            #print(X)
        
Xtest = []
ytest = []
with open("demo-test.txt", 'r', encoding='utf8') as f:
    Xtest = []
    ytest = []
    for line in f:
        if line != "":
            vals = line.split()
            Xtest.append([float(val) for val in vals[:-1]])
            ytest.append(int(vals[-1]))
        


In [9]:
        
X = np.array(X)          # the 4 lines are optional - It runs fine with Python lists.  For large dataset numpy arrays are better
y = np.array(y)
print(X)
Xtest = np.array(Xtest)
ytest = np.array(ytest)

[[2.         3.         3.         3.         4.40671925]
 [2.         1.         3.         0.         4.63472899]
 [6.         2.         3.         0.         4.92725369]
 ...
 [4.         3.         2.         0.         4.54329478]
 [2.         1.         2.         0.         4.39444915]
 [5.         1.         0.         0.         3.8918203 ]]


In [5]:
X.shape

(1276, 5)

In [6]:
# classifies data using both methods: one versus reast and multinomial
for mclass in ('multinomial', 'ovr'):
    lr = LogisticRegression(solver='lbfgs', max_iter=200, random_state=0, multi_class=mclass).fit(X, y)
    yhat = lr.predict(Xtest)
     
    # the 3 lines below show how to invoke various output    
    print("\n",mclass,"Accuracy",accuracy_score(ytest, yhat))
    print("\n",mclass,"Classification Report\n",classification_report(ytest, yhat),sep="")
    print("\n",mclass,"Classification Report\n",confusion_matrix(ytest, yhat),sep="")


 multinomial Accuracy 0.6033333333333334

multinomialClassification Report
              precision    recall  f1-score   support

           1       0.05      0.50      0.08         2
           2       0.00      0.00      0.00         1
           3       0.11      0.21      0.14        14
           4       0.18      0.09      0.12        55
           5       0.81      0.75      0.78       228

   micro avg       0.60      0.60      0.60       300
   macro avg       0.23      0.31      0.23       300
weighted avg       0.65      0.60      0.62       300


multinomialClassification Report
[[  1   0   1   0   0]
 [  0   0   0   0   1]
 [  2   3   3   3   3]
 [  6   1   7   5  36]
 [ 13   6  17  20 172]]

 ovr Accuracy 0.63

ovrClassification Report
              precision    recall  f1-score   support

           1       0.05      0.50      0.09         2
           2       0.00      0.00      0.00         1
           3       0.17      0.29      0.22        14
           4       0.1

In [7]:
# other functions you might find helpful

# a multi-sentence review (string)
areview = "Have had Alexa for over a week and we make a great pair. I live alone and now don't feel alone. She gives me the weather reminds me of what I have to do, groceries, great music and very hokey jokes. Best investment I've made in years. Re-named her Echo cause I forget the name Alexa, wish we could pick our own name?? Set up the Crash from Dory alarm the next day. It went off LOUD hearing a mans voice in the house startled and and the dogs freaked too...it was funny afterwards."
print("The review:",areview)

# the review string segmented into sentences
sntlst = sent_tokenize(areview)
print("\nSegmented sentences:",sntlst)

# (word) tokenizing the first sentence
first_toks = word_tokenize(sntlst[0])
print("\nFirst sentence (word) tokenized:",first_toks)

# part-of-speech tagging the tokenized first sentence:
print("\nFirst sentence pos-tagged:",pos_tag(first_toks))



The review: Have had Alexa for over a week and we make a great pair. I live alone and now don't feel alone. She gives me the weather reminds me of what I have to do, groceries, great music and very hokey jokes. Best investment I've made in years. Re-named her Echo cause I forget the name Alexa, wish we could pick our own name?? Set up the Crash from Dory alarm the next day. It went off LOUD hearing a mans voice in the house startled and and the dogs freaked too...it was funny afterwards.

Segmented sentences: ['Have had Alexa for over a week and we make a great pair.', "I live alone and now don't feel alone.", 'She gives me the weather reminds me of what I have to do, groceries, great music and very hokey jokes.', "Best investment I've made in years.", 'Re-named her Echo cause I forget the name Alexa, wish we could pick our own name??', 'Set up the Crash from Dory alarm the next day.', 'It went off LOUD hearing a mans voice in the house startled and and the dogs freaked too...it was fu

LookupError: 
**********************************************************************
  Resource averaged_perceptron_tagger not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('averaged_perceptron_tagger')
  
  Attempted to load taggers/averaged_perceptron_tagger/averaged_perceptron_tagger.pickle

  Searched in:
    - '/home/loki/nltk_data'
    - '/home/loki/anaconda3/nltk_data'
    - '/home/loki/anaconda3/share/nltk_data'
    - '/home/loki/anaconda3/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************
